{
 "title": "Custom",
 "tags": [ "wan" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "wan1,wan2" }
  ]
 },
 "panels": [
  {
   "title": "Live Endpoints (mk*)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": " min({$ClusterFilterLabel=\"$Cluster\", tag=\"WanDiscovery-mk\"})",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "Dead Endpoints (mk*)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{$ClusterFilterLabel=\"$Cluster\", tag=\"WanDiscovery-mk\"})",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "All Endpoints (mk*)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "min(org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{$ClusterFilterLabel=\"$Cluster\", tag=\"WanDiscovery-mk\"})",
     "legendFormat": "Dead"
    }
   ]
  },
  {
   "title": "WAN Outbound Queue Sizes (mk*)",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_outboundQueueSize{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=custom\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "WAN Endpoints (mk*)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(org_hazelcast_addon_IpDiscoveryStatus_DeadTargetEndpointCount{$ClusterFilterLabel=\"$Cluster\", tag=\"WanDiscovery-mk\"})",
     "legendFormat": "Dead"
    },
    {
     "expr": "min(org_hazelcast_addon_IpDiscoveryStatus_LiveTargetEndpointCount{$ClusterFilterLabel=\"$Cluster\", tag=\"WanDiscovery-mk\"})",
     "legendFormat": "Live"
    },
    {
     "expr": "min(org_hazelcast_addon_IpDiscoveryStatus_TargetEndpointCount{$ClusterFilterLabel=\"$Cluster\",  tag=\"WanDiscovery-mk\"})",
     "legendFormat": "All"
    }
   ]
  },
  {
   "title": "Outbound Queue Sizes",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_outboundQueueSize{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=custom\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}