{
 "title": "Executors",
 "tags": [
  "hazelcast",
  "executor"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "myhz1,myhz2,wan1,wan2" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Executors",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_creationTime{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalExecutionTime{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalStartLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_started{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_remainingQueueCapacity{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_poolSize{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_queueSize{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_pending{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_maximumPoolSize{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_completedTasks{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_completed{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_cancelled{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executors: Execution Count",
   "type": "barchart",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_started{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_completed{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_cancelled{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Executors: Max Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(com_hazelcast_Metrics_queueSize{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor.internal\"})",
     "legendFormat": "Max Queue Size"
    }
   ]
  },
  {
   "title": "Executors: Total Execution Count",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_completed{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"})",
     "legendFormat": "{{instance}} Total Completed"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_cancelled{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"})",
     "legendFormat": "{{instance}} Total Cancelled"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_started{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"})",
     "legendFormat": "{{instance}} Total Started"
    }
   ]
  },
  {
   "title": "Executors: Average Execution Latency",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalExecutionTime{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}/(com_hazelcast_Metrics_completed{$ClusterFilterLabel=\"$Cluster\",prefix=\"executor\"}+com_hazelcast_Metrics_cancelled{job=\"$Cluster\",prefix=\"executor\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}