{
 "title": "Member",
 "tags": [
  "hazelcast",
  "member",
  "single"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "myhz1,myhz2,wan1,wan2" },
   {
    "name": "Member",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_nodes{$ClusterFilterLabel=\"$Cluster\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "Member" },
  {
   "title": "Hazelcast Cluster Member",
   "type": "text",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 1 },
   "options": { "content": "# ${Member}" },
   "targets": [
    { "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory: Free, Used",
   "type": "piechart",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedMemory{instance=\"$Member\"})",
     "legendFormat": "Used Memory"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeMemory{instance=\"$Member\"})",
     "legendFormat": "Free Memory"
    }
   ]
  },
  {
   "title": "Member Resources",
   "type": "table",
   "gridPos": { "h": 6, "w": 16, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory{instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMemory{instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedMemory{instance=\"$Member\"}/com_hazelcast_Metrics_totalMemory{instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_usedNative{instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_committedNative{instance=\"$Member\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{instance=\"$Member\", gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{instance=\"$Member\", gc=~\".+Old Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_count{instance=\"$Member\", gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "jvm_gc_collection_seconds_sum{instance=\"$Member\", gc=~\".+Young Generation\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Load (Per Member)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_systemCpuLoad{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Swap Space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalSwapSpaceSize{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GC Count: Minor, Major",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max(jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", gc=~\".+Young Generation\"})",
     "legendFormat": "GC Minor Count"
    },
    {
     "expr": "max(jvm_gc_collection_seconds_count{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", gc=~\".+Old Generation\"})",
     "legendFormat": "GC Major Count"
    }
   ]
  },
  {
   "title": "Used Native",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedNative{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": " Heap: Used, Free, Max",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"})",
     "legendFormat": "Used Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeHeap{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"})",
     "legendFormat": "Free Heap"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_maxHeap{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Used Heap",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_usedHeap{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Used Memory Maps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_usedMemory{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"})",
     "legendFormat": "Used Memory Maps"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_freeMemory{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"})",
     "legendFormat": "Free Memory"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_maxHeap{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"})",
     "legendFormat": "Max Heap"
    }
   ]
  },
  {
   "title": "Thread Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_threadCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "Data Structures", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 } },
  {
   "title": "Lists",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_creationTime{instance=\"$Member\", prefix=\"list\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_lastUpdateTime{instance=\"$Member\", prefix=\"list\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_lastAccessTime{instance=\"$Member\", prefix=\"list\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_lockedEntryCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupEntryCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"map\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_dirtyEntryCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"map\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMaxPutLatency{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMaxGetLatency{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMaxSetLatency{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMaxRemoveLatency{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PN Counters",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_creationTime{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"pnCounter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalIncrementOperationCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"pnCounter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalDecrementOperationCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"pnCounter\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_value{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"pnCounter\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Queues",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 65 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedItemCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupItemCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_maxAge{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_minAge{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_averageAge{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOffers{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfPolls{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"queue\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"queue\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Replicated Maps",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMaxPutLatency{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalMaxGetLatency{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_maxPutLatency{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_maxGetLatency{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_maxRemoveLatency{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"replicatedMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sets",
   "type": "table",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_creationTime{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"set\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_lastUpdateTime{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"set\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_lastAccessTime{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"set\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Topics",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalPublishes{instance=\"$Member\", prefix=\"topic\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalReceivedMessages{instance=\"$Member\", prefix=\"topic\"} ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Reliable Topics",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalPublishes{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"reliableTopic\"} ",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalReceivedMessages{$ClusterFilterLabel=\"$Cluster\", instance=\"$Member\", prefix=\"reliableTopic\"} ",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}