{
 "title": "Multi Maps Rows Charts",
 "tags": [
  "hazelcast",
  "data structure",
  "multimap"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "myhz,wan1,wan2" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "Multi Maps: Entries",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Entry Memory",
   "type": "barchart",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Events",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Hits",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Put Count",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Get Count",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Query Count",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_queryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Remove Count",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Put Latency",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalMaxPutLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Set Latency",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalMaxSetLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Get Latency",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalMaxGetLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Multi Maps: Total Remove Latency",
   "type": "barchart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_totalMaxRemoveLatency{$ClusterFilterLabel=\"$Cluster\",prefix=\"multiMap\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}