{
 "title": "Queue",
 "tags": [
  "hazelcast",
  "data structure",
  "queue"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "myhz,wan1,wan2" },
   {
    "name": "Queue",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_creationTime{prefix=\"queue\"},tag0)"
    }
   },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "$Queue: All",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_maxAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_minAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_averageAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfPolls{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Queue: Items",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_backupItemCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Queue: Age",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_maxAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_minAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_averageAge{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Queue: Operations",
   "type": "barchart",
   "gridPos": { "h": 16, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfPolls{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_total{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfOtherOperations{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfRejectedOffers{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "$Queue: Events",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\",prefix=\"queue\", tag0=\"\\\"name=$Queue\\\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}