{
 "title": "Replicated Map",
 "tags": [
  "hazelcast",
  "data structure",
  "replicatedmap"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "myhz,wan1,wan2" },
   {
    "name": "Map",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_entryCount,tag0)"
    }
   },
   { "name": "MapType", "label": "Map Type", "query": "map" }
  ]
 },
 "panels": [
  {
   "title": "$Map: Entries, Memory ($MapType)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\",prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Entries"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\",prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "$Map: Operations/s ($MapType)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalPutLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Puts/s"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalGetLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Gets/s"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalRemoveLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Removes/s"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_setCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})*1000/sum(com_hazelcast_Metrics_totalSetLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Sets/s"
    }
   ]
  },
  {
   "title": "$Map: Dirty Entries ($MapType)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_dirtyEntryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Dirty Entries"
    }
   ]
  },
  {
   "title": "$Map: Backup ($MapType)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(com_hazelcast_Metrics_backupEntryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Backup Entries"
    },
    {
     "expr": "sum(com_hazelcast_Metrics_backupEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"})",
     "legendFormat": "Backup Memory"
    }
   ]
  },
  {
   "title": "$Map: Map Statistics ($MapType)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_ownedEntryCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Entries"
    },
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Gets"
    },
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Puts"
    },
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Removals"
    },
    {
     "expr": "com_hazelcast_Metrics_setCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Sets"
    },
    {
     "expr": "com_hazelcast_Metrics_ownedEntryMemoryCost{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Entry Memory"
    },
    {
     "expr": "com_hazelcast_Metrics_numberOfEvents{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Events"
    },
    {
     "expr": "com_hazelcast_Metrics_hits{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\",tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Hits"
    }
   ]
  },
  {
   "title": "$Map: Map Throughput Statistics ($MapType)",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}*1000/com_hazelcast_Metrics_totalPutLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Puts"
    },
    {
     "expr": "com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}*1000/com_hazelcast_Metrics_totalGetLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}\n",
     "legendFormat": "Gets"
    },
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_totalRemoveLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Removals"
    },
    {
     "expr": "com_hazelcast_Metrics_setCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}*1000/com_hazelcast_Metrics_totalSetLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Sets"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPutLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_putCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    },
    {
     "expr": "com_hazelcast_Metrics_totalGetLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_getCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    },
    {
     "expr": "com_hazelcast_Metrics_totalRemoveLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    },
    {
     "expr": "com_hazelcast_Metrics_totalSetLatencies{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}/com_hazelcast_Metrics_setCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"$MapType\", tag0=\"\\\"name=$Map\\\"\"}",
     "legendFormat": "Avg Get Put Latency"
    }
   ]
  }
 ]
}