{
 "title": "WAN",
 "tags": [
  "hazelcast",
  "wan"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "ClusterFilterLabel", "query": "job" },
   { "name": "Cluster", "query": "myhz,wan1,wan2" },
   {
    "name": "Wan",
    "label": "WAN",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_outboundQueueSize{prefix=\"wan\", $ClusterFilterLabel=\"$Cluster\"},tag1)"
    }
   },
   {
    "name": "WanPublisherId",
    "label": "Publisher",
    "query": {
     "query": "label_values(com_hazelcast_Metrics_outboundQueueSize{prefix=\"wan\", $ClusterFilterLabel=\"$Cluster\", tag1=~\"\\\"replication=$Wan\\\"\"},tag0)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Members",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_outboundQueueSize{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_queueFillPercent{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPublishLatency{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_totalPublishedEventCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag1=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayLastStart{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayLastEnd{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayTotalCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "com_hazelcast_Metrics_ackDelayTotalMillis{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Update Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_updateCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Remove Events",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_removeCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Entry Sync Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_syncCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Maps: Dropped Entry Events",
   "type": "table",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "targets": [
    {
     "expr": "com_hazelcast_Metrics_droppedCount{$ClusterFilterLabel=\"$Cluster\", prefix=\"wan\", tag0=\"\\\"publisherId=$WanPublisherId\\\"\", tag2=\"\\\"replication=$Wan\\\"\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}