#!/usr/bin/env bash

# ========================================================================
# Copyright (c) 2020-2023 Netcrest Technologies, LLC. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ========================================================================

SCRIPT_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"
. $SCRIPT_DIR/.addonenv.sh

EXECUTABLE="`basename $0`"

if [ "$HELP" == "true" ]; then
cat <<EOF

WORKSPACE
   $PADOGRID_WORKSPACE

NAME
   $EXECUTABLE - Ingest data to all of the supported data structures

SYNOPSIS
   $EXECUTABLE [-cluster myhz1|myhz2|wan1|wan2] [-?]

DESCRIPTION
   Cleans the 'results' directory by removing all files.   

OPTIONS
   -cluster myhz1|myhz2|wan1|wan2
            Target cluster. Default: myhz1

EOF
exit
fi

./test_ingestion -cluster $CLUSTER_ARG -run
./test_summary -cluster $CLUSTER_ARG -run
./test_group -cluster $CLUSTER_ARG -run
./test_group -cluster $CLUSTER_ARG -run -prop ../etc/group-queue.properties
./test_group -cluster $CLUSTER_ARG -run -prop ../etc/group-rmap.properties
./test_group -cluster $CLUSTER_ARG -run -prop ../etc/group-rtopic.properties
./test_group -cluster $CLUSTER_ARG -run -prop ../etc/group-topic.properties
