global:
  scrape_interval:     5s
  external_labels:
    monitor: 'hazelcast'

scrape_configs:
  - job_name: 'wan1'
    scrape_interval: 2s
    static_configs:
      - targets: [localhost:8591, localhost:8592, localhost:8593, localhost:8594, localhost:8595, localhost:8596, localhost:8597, localhost:8598, localhost:8599, localhost:8600]
  - job_name: 'wan2'
    scrape_interval: 2s
    static_configs:
      - targets: [localhost:8691, localhost:8692, localhost:8693, localhost:8694, localhost:8695, localhost:8696, localhost:8697, localhost:8698, localhost:8699, localhost:8700]
